# Generated by Django 3.1.3 on 2020-11-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diff',
            name='field',
            field=models.CharField(blank=True, choices=[('birthday', 'birthday'), ('email', 'email'), ('birthplace', 'birthplace'), ('date_expiration', 'date_expiration'), ('username', 'username'), ('last_name', 'last_name'), ('document_type', 'document_type'), ('card_number', 'card_number'), ('date_issue', 'date_issue'), ('middle_name', 'middle_name'), ('card_holder', 'card_holder'), ('expiry_date', 'expiry_date'), ('first_name', 'first_name'), ('number', 'number'), ('gender', 'gender'), ('phone', 'phone'), ('series', 'series'), ('bank_name', 'bank_name'), ('bank_alias', 'bank_alias'), ('photo', 'photo')], max_length=255, null=True, verbose_name='Поле'),
        ),
    ]
